### ISSUE TITLE
low fps

### ISSUE THREAD

**Issue by ghost** [prscX/react-native-styled-dialogs#3]
👍  thank for this work .  low ui  & js fps : ~1-4 fps  :
"react": "^16.6.1",
 "react-native": "^0.57.7",
buildToolsVersion = "27.0.3"
compileSdkVersion = 27
targetSdkVersion = 26

**Comment by prscX** [comment]
Thanks @hsxb95 for raising the issue.

Could you please elaborate the issue. I am not able to understand the problem which you are facing.

Thanks
</ Pranav >
